### ISSUE TITLE
POM files and server configuration cleanup

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-jwt#12]
- [x] The parent pom.xml contains many out-of-date or inapplicable references that should be removed or cleaned up from repositories, dependencies to properties;

- [x] The same applies to all the other POMs -- Should keep all POM files clean and simple;

  - Remember camel case too;

- [x] Copyright statements need to be accurate or be removed;

- [x] Do we actually need and use jwt.shared.key?  We are using keys in keystore, correct?

- [x] Should we have a different value for jwt.issuer like openliberty.io?

- [x] Why do we need jti=true?

**Comment by JunyiSun** [comment]
Unsolved issues from the peer review:

- [ ] `finish/pom.xml` has duplicate dependencies defined in `depedencies` and under `dependencyManagement`. Most importantly, these are test dependencies but they have scopes set to "compile". Why do you need test libraries at compile time (these only seem to matter for the `resource` project)? I suspect that this is because your tests are defined under the `main` directory, while they should be under the `test` directory and the integration test plugin should then point to that test directory. In any case, unless this inentional, this needs to be fixed, otherwise its just inconsistent with other guides and all in all just bad practice.

- [ ] Decencies in `finish/resources/pom.xml` are either all missing version or don't need scopes because they are already defined in the parent pom

**Comment by JunyiSun** [comment]
@jamiecoleman92 is fixing this issue.

**Comment by JunyiSun** [comment]
Since @jamiecoleman92 is on vacation, I will take over this issue.

**Comment by yeekangc** [comment]
The latest in master seems fine.  Closing.
